### ISSUE TITLE
如何关掉上传图片功能，直接改js？

### ISSUE THREAD

**Issue by monyuan** [fooleap/disqus-php-api#49]
RT

**Comment by fooleap** [comment]
1. 可直接添加 CSS：
```css
.comment-image-input + .comment-actions-label {
    display: none;
}
```
2. 更新最新代码后，在 Disqus 后台的 settings -> community 的 `Enable Media Attachments` 设置将生效。
